### ISSUE TITLE
Please prefer package.mask to KEYWORDing ghc releases

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1047]
As i've noted twice in #gentoo-haskell, it would be much more comfortable for both users and maintainers to have the new releases masked in `package.mask` as opposed to the `KEYWORDS` ebuild variable, as unmasking then would only require removing/copying the corresponding chunk of lines from `package.mask`, while in case of `KEYWORDS` it would require a dozen or two runs of `emerge` to figure all the dependencies that are needed to be put to `package.keywords` file. Also, it doesn't conform to the `KEYWORDS` purpose outlined in ebuild(5).

Is there a reason that you still prefer the `KEYWORDS` abuse?

**Comment by trofi** [comment]
`KEYWORDS` can be re-added per-arch basis easily. `package.mask` can't.

**Comment by l29ah** [comment]
ghc releases are known to be tested on a certain set of architectures by the ghc maintainers, so you don't need to re-~keyword them individually after a version bump. Also, as it works on your machine, you could have ~keyworded for its architecture, but you haven't.

**Comment by trofi** [comment]
Gentoo has to build their own binaries architecture at a time. We keyword ebuilds only after Gentoo binaries are ready (and most of reverse dependencies are not broken). Otherwise you won't be able to build a compiler even if you have keywords.

**Comment by l29ah** [comment]
I was building my compiler exclusively via USE=ghcbootstrap for the last couple of years, and i've never needed the binaries you're talking about.

**Comment by trofi** [comment]
Others `USE=ghcbootstrap` users were not as lucky as you: https://bugs.gentoo.org/show_bug.cgi?id=695738 Recent `libffi` update broke `USE=ghcbootstrap` at least twice in past year. But it does not matter.

`USE=ghcbootstrap` is not a supported configuration for end-users (and thus is not a default) precisely because system compiler is a lot simpler to break than a specifically prebuilt binary that bundles things like `libffi` and avoids `ncurses` dependencies.

**Comment by l29ah** [comment]
Okay, how do you unmask a specific complete ghc release stuff w/o multiple emerge runs? The rest of ghc libraries are KEYWORDed away too, yet this logic doesn't extend to them.

**Comment by solpeth** [comment]
> As i've noted twice in #gentoo-haskell, it would be much more comfortable for both users and maintainers to have the new releases masked in `package.mask` as opposed to the `KEYWORDS` ebuild variable

As a ::haskell maintainer I have to disagree. The way in which we remove and re-add keywords as arches meet the requirements set out in our ghc keywording docs is flexible. We did agree to put the masks in place as you suggest, but I personally found no utility in it for maintainership. 

As for the end-user, my perspective is that masks of any form are in place because those package versions aren't yet ready for widespread use. Of course, Gentoo gives you the freedom to unmask and keyword whichever packages you like, but this freedom is predicated on the understanding that the user is wading into unsupported configurations, and is therefore more or less on their own.

The way we unkeyword our packages as opposed to using `package.mask` isn't to make it harder for end users. It's primarily for us to have the smoothest method of maintainership, and to keep end users, on the whole, in supported configurations by default until we can be satisfied that packages can be keyworded.

All views are my own and not necessarily those of other maintainers.

**Comment by trofi** [comment]
> Okay, how do you unmask a specific complete ghc release stuff w/o multiple emerge runs?

There is no simple way to unmask only a specific release. Same as there is no simple way to install older stable ghc release without getting into problems with duplicate libraries. It's an orthogonal problem to typical use cases.

Typical use cases are:
- use latest stable: don't tweak KEYWORDS
- use latest ~arch: use `*/*::haskell` KEYWORDS
- use latest unkeyworded packages: use `*/*::haskell` KEYWORDS and a few unversioned `**` keywords, like `cabal`, `transformers` & co.

Outside that you are on your own to find matching version that work. We need better dependency story to cover more cases.

> The rest of ghc libraries are KEYWORDed away too, yet this logic doesn't extend to them.

I'm not sure what that means. Some bundled libraries have to be updated in a lockstep with ghc. No ghc keywords -> no bundled library keywords. We try to extend keywords back to them once ghc is keyworded. Idealy such libraries should not ever present as standalone ebuilds, but practicaly it's hard because ghc adds and removes bundled exported libraries all the time.

**Comment by markwright** [comment]
To unmask ghc 8.10.1 and everything to be at the bleeding edge: add to /etc/portage/package.accept-keywords:

```
# ghc 8.10.1
=dev-lang/ghc-8.10* **
=dev-haskell/ghc-api-8* **
=dev-haskell/ghc-paths-0.1.0.12* **
=dev-haskell/binary-0.8.8.0* **
=dev-haskell/cabal-3.2.0.0* **
=dev-haskell/cabal-install-3.2.0.0* **
=dev-haskell/haddock-api-2.24.0* **
=dev-haskell/haddock-2.24.0* **
=dev-haskell/haddock-library-1.9.0* **
=dev-haskell/haskeline-0.8.0.0* **
=dev-haskell/parsec-3.1.14.0* **
=dev-haskell/stm-2.5.0.0* **
=dev-haskell/terminfo-0.4.1.4* **
=dev-haskell/text-1.2.3.2* **
```

And then a start is to copy everything from:
/var/lib/layman/haskell/profiles/package.mask
to:
/etc/portage/package.unmask
