### ISSUE TITLE
Add dependency check to CI

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/gentoo-haskell#1133]
Based on a comment [here](https://github.com/gentoo-haskell/gentoo-haskell/pull/1118#discussion_r559643302), I wanted to open this issue in order to not lose track of the suggestion.

Specifically:

> It causes me troubles if commit adds a package with missing dependencies. I usually find broken deps too late. Maybe we should try to enforce it in presubmit check. Should not be too hard.

The proposal is to add a step to the CI which checks dependencies of any new packages, i.e. `emerge -pe ${list_of_new_packages}` should not show any issues.

**Comment by ezzieyguywuf** [comment]
Hrm, although doesn't repoman already complain if a package has a "non-existent dep"?

**Comment by trofi** [comment]
`repoman` / `pkgcheck` does check deps, but it only does for the final repository state. Would be nice to check every commit in proposed branch in sequence.

**Comment by solpeth** [comment]
I've read the linked comment, and I have some questions if anyone has the time to chime in:

Is the issue that reverse dependencies are having their dependencies silently removed, and our QA tools don't tell us this on a per-commit basis?

Or is the issue that reverse dependencies are being added prior to all of their dependencies, in the correct order?

If it is scenario one, I have nothing to add.

If it is scenario two, however, does not using `repoman commit` mitigate most of the issues as regards ordering dependencies _before_ the reverse dependency? For example, the latest `pandoc` bump to 2.11 I did had both pkgcheck and repoman spitting 'non-existent dependency' issues at me, thus refusing to commit until I had committed each of the new `pandoc` dependencies (which in turn may have had further non-existent dependencies of their own, but `repoman commit` would have told me of this). 

To get around issues when cherry-picking commits which end up being masked, would it suffice to run `pkgcheck scan --commits` to check for non-existent dependencies of the cherry-picked commits against `master`? Because I can see what you mean that there is a tendency towards repo inconsistency between commits due to the 'one change/bump/file per commit' policy, especially when it comes to writing masks into `package.mask` (which I do before committing masked packages, otherwise repoman would not necessarily let me commit anything else).

I have more thoughts and topics to raise and consider but I am extremely short of time lately. I'll have to pick up on this more later.

**Comment by trofi** [comment]
`repoman commit` is usually enough. But complicated rebases might bet commit sequence into inconsistent state. `pkgcheck scan --commits` does not seem to do the right thing here.

**Comment by ezzieyguywuf** [comment]
the issue with `repoman commit` is that it cannot be used *after the fact* for QA, right? Instead, it must be used to perform the actual commit.

**Comment by hololeap** [comment]
With the new tooling, my workflow usually consists of:

* ```bash
  pkgdev manifest
  ```
* ```bash
  pkgcheck scan
  ```
* ```bash
  git add .
  ```
* ```bash
  pkgdev commit
  ```

Contributors will have CI checks run in any PRs they open, and devs should try to push to their own forks before pushing directly to `master` to make sure all checks pass.

I don't see any problem with this workflow, so I will close this. Feel free to reopen if you see any current issues with this.
