### ISSUE TITLE
Ebuild for GHC 8.10.7

### ISSUE THREAD

**Issue by Anrock** [gentoo-haskell/gentoo-haskell#1226]
It was realesed quite some time ago. Please provide a ebuild.

**Comment by hololeap** [comment]
We had some infrastructure issues on the last GHC release where people were having a hard time getting the bootstrap binaries, and we may run into the same issue again with a new GHC release.

@solpeth any comment on this?

**Comment by Anrock** [comment]
@solpeth since you're not really interested in 8.10.7 maybe there is an instructions/tips/procedure of writing ebuild for new ghc version? So I can try to do it myself and submit here.

**Comment by solpeth** [comment]
Very much interested, just time-poor unfortunately!

GHC bumping is a bit more involved than updating the ebuild. Roughly:

1. Bump the ebuild version
2. Mark bundled libraries across `::haskell` with `CABAL_CORE_LIB_GHC_PV` (find the list on the libraries section of the ghc release notes)
3. (only for major version bumps) Build at least 75% of `::haskell` as well as the list of core packages, otherwise just building your local haskell environment plus the core packages list in [this doc](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/projects/doc/HOWTO-keyword-ghc.rst#minimal-requirement-of-keyworded-ghc) should suffice
4. Generate binaries with `refresh-ghc-bin-haskell.bash` (found in the projects/ directory in the `::haskell` repo) so that `::haskell` users can have guaranteed ghc upgrade success (what this does is build a ghc binary which will then be used to build the newest ghc version for the `::haskell` user, as using whatever version the user has installed can cause all sorts of unpredictable upgrade failures).

All of these builds need to have tests enabled (although not all of them will necessarily pass).

If you would like to give any of this a go I would be more than happy to help wherever I can. Thanks for your interest!

**Comment by Anrock** [comment]
Okay, so far I've
1. Bumped ebuild
2. Added `PM:8.10.7` to `CABAL_CORE_LIB_GHC_PV` to all ebuilds I could frind from GHC libraries list
Couldn't find ebuilds for
* Win32 2.6.2.1
* array 0.5.4.0
* base 4.14.3.0
* ghc-compact 0.1.0.0
* ghc-prim 0.6.1
* hpc 0.6.1.0
* integer-gmp 1.0.3.0
* template-haskell 2.16.0.0

And for, though there were some -generic/-compat/-etc versions.
* bytestring 0.10.12.0
* containers 0.6.5.1
* deepseq 1.4.4.0
* directory 1.3.6.0 
* filepath 1.4.2.1 
* pretty 1.1.3.6 
* process 1.6.13.2 
* time 1.9.3 
* unix 2.7.2.2 
 3. Succesfully emerged 8.10.7 with `ghcbootstrap` flag (via `emerge -avuDN world`) and along some packages that needed rebuild. Then emerged core packages from provided list (xmonad, pandoc, hackport, darcs).

Now I'm reemerging dev-haskell packages with test.

**Comment by Anrock** [comment]
Seems like everything is fine with test packages.

@solpeth it's a little bit unclear how to use `refresh-ghc-bin-haskell.bash` script. I've tried executing `./refresh-ghc-bin-haskell.bash --target-arch=amd64 --temp-tmpfs` (from example inside), but it fails right at the beginning during downloads getting 404 for `http://distfiles.gentoo.org/releases/amd64/autobuilds/latest-stage3-amd64.txt` and receiving `index.html` instead of some kind of archive from `http://distfiles.gentoo.org/releases/amd64/autobuilds/`.

Do I use script incorrectly or it needs some updating?

**Comment by solpeth** [comment]
Sorry, @Anrock ! You were indeed using the script correctly (although I would also add `--needed-atom='=dev-lang/ghc-8.10.7`, which needs to already be in `::haskell` to work). You actually discovered a bug whose fix I need to push to the script in the repo: the stage3 url has changed.

@hololeap and I are actively working to get ghc-9.0.2 keyworded as soon as possible - although it is not ghc-8.10.7, it seems to come with some significant improvements that I think you would enjoy. Our outstanding issues are rebuilding most of ::haskell to prove that the new compiler can build it all, and regenerating the ghc-9.0.2 binaries (which is more an infra issue than actually generating them).

We'll get there ASAP.

**Comment by Anrock** [comment]
@solpeth thanks. As I was saying I need 8.10.7 specifically since this is the version my company uses at the moment. 9.x is surely better and all that, but I guess we're not upgrading in close future. 

So what are my next steps to make 8.10.7 happen in this overlay? Wait for you to fix the script, then try running it again? So far I've put the ebuild in my local repo and it seems to be working fine.

**Comment by hololeap** [comment]
@Anrock I added `ghc-8.10.7` but have not tested it. You'll have to set up your config like this:

`/etc/portage/package.use/haskell`
```
~dev-lang/ghc-8.10.7 ghcbootstrap
```

`/etc/portage/package.accept_keywords/haskell`
```
~dev-lang/ghc-8.10.7 **
```

Let us know if you have any problems.

**Comment by dorrellmw** [comment]
The new issue I just submitted, #1246, is related to this one.

**Comment by hololeap** [comment]
`ghc-8.10.7` has been added (unkeyworded) and it seems to be working on my end.

@Anrock you may want to add this configuration so that you don't accidentally upgrade later when we keyword `ghc-9.0.2`:

`/etc/portage/package.mask/haskell`
```
>=dev-lang/ghc-9
```

I'm closing this as the current state of the tree should be fine for those needing `ghc-8.10.7`.
