### ISSUE TITLE
Agda and Agda-stdlib out of date

### ISSUE THREAD

**Issue by aureliocarlucci** [gentoo-haskell/gentoo-haskell#1234]
The ebuilds provided for _agda_ and _agda-stdlib_ are out of date. The former is available only for version 1.6.2, while both ebuilds rely on v1.4 of the _agda-stdlib_:

https://github.com/gentoo-haskell/gentoo-haskell/blob/339e665bed3bdfc479d3c844ecd332b1f6533c8e/sci-mathematics/agda/agda-2.6.1.2.ebuild#L21

which is currently at [version](https://github.com/agda/agda-stdlib/releases/tag/v1.7.1) 1.7

I understand that these ebuilds are hand-crafted, instead of being generated by _hackport_, so it is not obvious how to update them, but I am happy to help.

**Comment by solpeth** [comment]
Thanks for the report!

I'll see if I can give it a go now. When I have more time I will get around to replying on how you could do this yourself - as that would be very helpful for all of us!

**Comment by aureliocarlucci** [comment]
Thanks for your reply. Looking forward to that!

**Comment by solpeth** [comment]
So my process has been:

1. `hackport merge` the new agda version (`2.6.2`)
2. Copy in all the handcrafted stuff from the previous version to the new version
3. Update the `stdlib` version in the `agda` ebuild to the version required by the new version of agda (in this case it seems to be `1.7.1`, so the version we would use for the stdlib is `2.6.2.1.7.1`)
4. Copy the `agda-stdlib` ebuild to a new version number combining the agda version number and the agda-stdlib version numbers together (i.e. `2.6.2.1.7.1`)
5. Update the version number within the `agda-stdlib` ebuild to the same one pointed to in the agda ebuild
6. Test that it builds, installs and runs properly.

That seems to have worked for me (and this all might make more sense if you look at the agda and agda-stdlib ebuilds while reading through the steps). If need be I'd be happy to answer questions so that, if you wanted, you could contribute to agda stuff going forward. Thanks!

In the mean time, this bug will be closed as resolved once the changes are pushed.

**Comment by aureliocarlucci** [comment]
Many thanks for doing this so promptly! Next time I will give it a go to bump-up the version myself.

**Comment by solpeth** [comment]
That sounds great! We can always do with more help. I look forward to your contributions!
