### ISSUE TITLE
dev-haskell/stack-2.7.4_pre20220125: dos2unix: [...]/stack.cabal: No such file or directory

### ISSUE THREAD

**Issue by LadyBoonami** [gentoo-haskell/gentoo-haskell#1281]
Greetings,

the build for dev-haskell-stack-2.7.4_pre20220125 fails for me.

emerge.log:
```
 * Package:    dev-haskell/stack-2.7.4_pre20220125
 * Repository: haskell
 * Maintainer: haskell@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   distcc network-sandbox preserve-libs sandbox usersandbox
>>> Unpacking source...
>>> Unpacking stack-9a0683679ad49982fcfb036f87c0f99a78916d2a.tar.gz to /var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work
>>> Source unpacked in /var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work
>>> Preparing source in /var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work/stack-9a0683679ad49982fcfb036f87c0f99a78916d2a ...
dos2unix: /var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work/stack-2.7.4_pre20220125/stack.cabal: No such file or directory
dos2unix: Skipping /var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work/stack-2.7.4_pre20220125/stack.cabal, not a regular file.
 * ERROR: dev-haskell/stack-2.7.4_pre20220125::haskell failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_prepare
 *   environment, line 1935:  Called haskell-cabal_src_prepare
 *   environment, line 1622:  Called die
 * The specific snippet of code:
 *       dos2unix "${cabal_file}" || die;
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/stack-2.7.4_pre20220125::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/stack-2.7.4_pre20220125::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work/stack-9a0683679ad49982fcfb036f87c0f99a78916d2a'
 * S: '/var/tmp/portage/dev-haskell/stack-2.7.4_pre20220125/work/stack-9a0683679ad49982fcfb036f87c0f99a78916d2a'
```
The path to `dos2unix` is wrong (`work/stack-2.7.4_pre20220125/stack.cabal`), the files are correctly located under `${S}` (`work/stack-9a0683679ad49982fcfb036f87c0f99a78916d2a`). I think this error is triggered by the recent changes to `haskell-cabal.eclass` in ea245047d18f82e05656f1664c12a53eaf9afd57, but I'm not sure whether the eclass or the ebuild is at fault here.

**Comment by hololeap** [comment]
@LadyBoonami 

The `$CABAL_FILE` variable, which was added in https://github.com/gentoo-haskell/gentoo-haskell/commit/ea245047d18f82e05656f1664c12a53eaf9afd57 like you mentioned, is set in the eclass based on the state of the `$S` variable when the eclass is loaded:

https://github.com/gentoo-haskell/gentoo-haskell/blob/52158ad59ceb77cfaea60314244892bb3f33d726/eclass/haskell-cabal.eclass#L156-L160

 So, in this case either the `$S` variable needs to be set pre-inherit so that `$CABAL_FILE` takes on the correct value, or `$CABAL_FILE` needs to be be explicitly set in the ebuild.

**Comment by LadyBoonami** [comment]
Perfect, thanks!

**Comment by hololeap** [comment]
It looks like the only way to get it to work consistently is to override `$S` _after_ the import, and then override `$CABAL_FILE`. I had to [revert](https://github.com/gentoo-haskell/gentoo-haskell/commit/0df0cadd71894c2ccd984624d07841478316e3f2) https://github.com/gentoo-haskell/gentoo-haskell/commit/21931f370d60a28cd6a43f2ad513ab7110d7ed42 because `$S` is already defined before the eclass is imported and it ends up keeping the ebuild from updating it.

https://github.com/gentoo-haskell/gentoo-haskell/issues/1282
