### ISSUE TITLE
dev-lang/ghc-9.2.6 fails to build on musl/clang profile

### ISSUE THREAD

**Issue by vimproved** [gentoo-haskell/gentoo-haskell#1399]
`build.log`: https://0x0.st/H-cA.log
`emerge --info`: https://0x0.st/H-ca.txt

The error in question appears to be this: ```hsc2hs: libraries/base/dist-install/build/GHC/Stats_hsc_make: createProcess: posix_spawnp: does not exist (No such file or directory)
libraries/array/ghc.mk:4: libraries/array/dist-install/build/.depend-v-dyn.c_asm: No such file or directory```

Also, the ebuild for ghc-9.2.6 does not respect CC for me, and fails without having `sys-devel/clang-toolchain-symlinks[gcc-symlinks]` installed.

**Comment by formula-spectre** [comment]
+1
this is my log; it's similar  
https://0x0.st/H-m_.log

**Comment by hololeap** [comment]
I didn't have any luck bootstrapping our `ghc-9.0.2` ebuild from [the `::clang-musl` version](https://github.com/clang-musl-overlay/clang-musl-overlay/tree/master/dev-lang/ghc) of `ghc-9.0.2`

`ghc-9.2.*` is going to be even worse off because there hasn't been any effort to enable the LLVM backend. I am hoping that [`hadrian`](https://gitlab.haskell.org/ghc/ghc/blob/master/hadrian/doc/flavours.md#flavour-transformers) will make this easier than `make` has.

Once https://github.com/gentoo-haskell/gentoo-haskell/pull/1397 has `hadrian` fleshed out a bit better, I would like to work on getting it backported to `ghc-9.2.6`, which will hopefully help get the ebuild working with musl/clang.

This is the roadmap for now, but any extra help is appreciated, of course.

---

Related: https://github.com/gentoo-haskell/gentoo-haskell/issues/1368

**Comment by vi-improved** [comment]
::clang-musl now has 9.2.6, I'll attempt to try it out.
