### ISSUE TITLE
app-text/pandoc does not install properly on amd64

### ISSUE THREAD

**Issue by jeffgazso** [gentoo-haskell/gentoo-haskell#1480]
The *pandoc* binary seems to be missing or not installed to an appropriate PATH location after emerging `app-text/pandoc` from the Gentoo Haskell repository. After installation, the *pandoc* 3.*x* man page is present indicating at least partial installation success.

I have only tested this on amd64, I have not tried to reproduce the issue on other architectures.

**Comment by l29ah** [comment]
Reproduced.

**Comment by hololeap** [comment]
This is an understandable confusion. `pandoc` is now purely a library and `pandoc-cli` is the package that contains the executable. This was changed a year ago: https://github.com/jgm/pandoc/commit/bd1d923b86edba6e090ba14b1cd17e1e32c727f2

Renaming `app-text/pandoc` to `dev-haskell/pandoc` may alleviate some confusion, since it would hint that `pandoc` is simply a Haskell lib, and `app-text/pandoc-cli` is the actual application.

**Comment by solpeth** [comment]
@hololeap I've been toying with the idea of adding an `executable` flag to the pandoc ebuild and a PDEPEND on `pandoc-cli`. Thoughts?

AFAIK we also have the post-install message about the binary but perhaps it is not clear enough.

**Comment by hololeap** [comment]
> I've been toying with the idea of adding an `executable` flag to the pandoc ebuild and a PDEPEND on `pandoc-cli`.

That doesn't sound like a bad idea.

> AFAIK we also have the post-install message about the binary but perhaps it is not clear enough.

Yeah, but sometimes those messages don't get read. https://github.com/gentoo-haskell/gentoo-haskell/commit/d7d13c0ee0af75839a2f607366dab6e990ebbe39
