### ISSUE TITLE
Build-test "core" packages on ghc-9.4

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1485]
These packages (and their whole dependency tree) will need to be built with `USE="test"` (and ideally `USE="examples executable hoogle hscolour profile"` to cover all bases), using the latest `ghc-9.4` version (currently `ghc-9.4.8` as of 2024-03-06).

- [X] `app-admin/haskell-updater`
- [X] `app-office/hledger`
- [X] `app-office/hledger-interest`
- [X] `app-office/hledger-ui`
- [X] `app-office/hledger-web`
- [X] `app-portage/hackport`
- [X] `app-text/pandoc`
- [X] `dev-haskell/cabal-install`
- [X] `dev-haskell/haskell-language-server`
- [X] `dev-haskell/hledger-lib`
- [X] `dev-haskell/hlint`
- [X] `dev-util/hadolint`
- [X] `dev-util/shellcheck`
- [X] `dev-vcs/darcs` -- Upstream has a new version `2.18.1`
- [X] `dev-vcs/git-annex`
- [X] `x11-misc/arbtt`
- [X] `x11-misc/xmobar`
- [X] `x11-wm/xmonad`
- [X] `x11-wm/xmonad-contrib`

**Comment by vimproved** [comment]
I've managed to build all of these, barring `dev-vcs/darcs` (requires text <2) and `x11-misc/xmobar` (`dev-haskell/glib` is broken on musl).

Here are logs for test failures:
dev-haskell/crypton: https://0x0.st/HyuL.log
dev-haskell/crypton-x509-validation: https://0x0.st/Hyu9.log
dev-haskell/hslua-core: https://0x0.st/Hyup.log
dev-haskell/tls: https://0x0.st/Hyuf.log
dev-haskell/tz (probably caused by musl): https://0x0.st/HyuO.log
dev-haskell/tzdata (probably caused by musl): https://0x0.st/HyuV.log
dev-haskell/unix-time: https://0x0.st/HyuW.log
x11-misc/arbtt (probably caused by musl): https://0x0.st/Hyu4.log
