### ISSUE TITLE
Hasktorch package request

### ISSUE THREAD

**Issue by LemonBreezes** [gentoo-haskell/gentoo-haskell#1534]
Hello. Would someone please package Hasktorch and add it to this repository? Doing ML in Haskell is really awesome.

**Comment by hololeap** [comment]
I wouldn't mind except

- The package seems to have some issues with newer GHC which we are in the process of moving to (see e.g. https://github.com/hasktorch/hasktorch/issues/689#issuecomment-1879296956)
- There is already a long list of packages that are being build-tested for the gentoo-haskell community.

  It would be better if you would be willing to package it yourself and submit the initial packages and any updates as pull requests to help distribute the work load and make sure it doesn't get broken (regularly build-testing _everything_ in the repo is infeasible so we try to focus on the most popular packages).

  There are some pages scattered around that may help get you started. Also, feel free to ask for help if you need it. We're in `#gentoo-haskell` on [libera.chat](https://libera.chat/) if you prefer IRC, just be patient since it's a low-traffic channel. Also `#gentoo-dev-help` (also on libera) is a general purpose channel for help writing ebuilds.
    - https://github.com/gentoo-haskell/hackport#readme
    - https://github.com/gentoo-haskell/gentoo-haskell/blob/master/scripts/doc/README.rst
    - https://github.com/gentoo-haskell/gentoo-haskell/blob/master/scripts/doc/HOWTO-contribute.rst
    - https://github.com/gentoo-haskell/gentoo-haskell/wiki/General-QA-tips
    - https://devmanual.gentoo.org/index.html
