### ISSUE TITLE
plans about GHC-9.10.1?

### ISSUE THREAD

**Issue by max-grek** [gentoo-haskell/gentoo-haskell#1541]
Hi, I don't know where to ask that question, so I wanna do that here.

Do you have any plans to add ghc-9.10.1 in overlay?

**Comment by l29ah** [comment]
Seems like i'm the one who is usually most interested in pulling new ghc versions, and this time i'm not planning it, since it's plenty of work (since most of hackage maintainers don't keep up with the latest ghc, and it needs boring work even when they do and produce new releases) and virtually no profit (no great improvements in 9.10).

**Comment by hololeap** [comment]
@max-grek 

`ghc-9.10.1.ebuild` is up, but you'll have to bootstrap it from `ghc-9.8` for now (install `ghc-9.8.2`, then follow [these instructions](https://github.com/gentoo-haskell/gentoo-haskell/wiki/Building-experimental-ghc) for the "bootstrap" installation type).

Also, I haven't tested past the GHC install, so you'll likely get lots of `setup: Encountered missing or private dependencies` errors as you try to install packages against this version of GHC (see [this](https://github.com/gentoo-haskell/gentoo-haskell/wiki/Understanding-the-Hackage-ecosystem) for more info).

**Comment by hololeap** [comment]
You don't have to bootstrap 9.10.1 anymore as of 27185cb8
