### ISSUE TITLE
haskell-platform package is stale

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#670]
The haskell-platform package is very outdated now. I see two reasonable options:

1. Update it with the latest package sets, as listed in https://www.haskell.org/platform/contents.html, but there will be a problem with portage thinking 2014.2.0.0 is newer than 8.2.2. The old versions should be removed or masked so portage updates correctly.
2. Remove haskell-platform from the tree entirely (or mask it). It's probably better to have no ebuild than it is to have old ebuilds.

The @haskell-platform set should probably be renamed as well, since without versions, it's not technically the "official" Haskell Platform. If the overlay maintainers disagree, someone should check with upstream to see if they mind using the phrase "Haskell Platform" for this purpose.

I personally don't know whether a certain version of the Haskell Platform specifies exact versions of included libraries or only minimum versions, but that should probably be decided upstream as well.

**Comment by solpeth** [comment]
It appears that the upstream haskell-platform is discontinued since the start of the ghc-8.8 series. There are no upper bounds in the [haskell-platform ebuild](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-haskell/haskell-platform/haskell-platform-2014.2.0.0-r1.ebuild), so it acts more like a meta-package of these common 'building-block' libraries more than anything, for whoever wants it.

Given that, I don't see the point in doing anything significant with this package.
