### ISSUE TITLE
stack profile flag seem has a lot of dependencies

### ISSUE THREAD

**Issue by VonFry** [gentoo-haskell/gentoo-haskell#694]
And those dependencies seem has something wrong with me.

I have to run `emerge` again and again to add new flag, and some of the pkgs appeared many times by different version in the same stack version.

This flag has the same description as ghc and cabal, but what can this do? Is it adding support  with `ghc profile` in stack? (I use haskell only for a litte time.)

By the way, I have remove the flag from my configure, so I cannot provide the dependencies error to contributors. Sorry.

**Comment by trofi** [comment]
Can you explain a few details?

1. What you are trying to achieve
2. What you are doing to achieve [1.]
3. What fails

**Comment by VonFry** [comment]
I am trying install `stack` and `cabal` with flag `profile`.

There are two question:

1. What dose `profile` flag support for in `stack`? I cannot understand the description. It is a global flag, but is it has the same feature as `stack --profile`?

2. There are too many dependencies. I have to run `emerge` to calculate dependencies many times to add some necessary use flag, but it seems some pkgs' flags always are missed to be set for me .

part of zz-autounmask file ( I have clean it before run `emerge` )

```
...

# required by dev-haskell/x509-store-1.6.2::haskell
# required by dev-haskell/x509-validation-1.6.5::haskell
# required by dev-haskell/tls-1.3.11::haskell
# required by dev-haskell/connection-0.2.8::haskell
# required by dev-haskell/http-client-tls-0.3.5.3::haskell
# required by dev-haskell/stack-1.5.1-r1::haskell
# required by @selected
# required by @world (argument)
=dev-haskell/cryptonite-0.23 profile

...

# required by dev-haskell/tls-1.4.1::haskell
# required by dev-haskell/connection-0.2.8::haskell
# required by dev-haskell/http-client-tls-0.3.5.3::haskell
# required by dev-haskell/http-conduit-2.2.4::haskell
# required by dev-haskell/stack-1.5.1-r1::haskell
# required by @selected
# required by @world (argument)
>=dev-haskell/cryptonite-0.25 profile

... 
```

`cryptonite` and some other packages are appeared twice or more times. Dose it mean these package s are needed by different version for different packages?

**Comment by trofi** [comment]
In Gentoo `USE=profile` for `dev-haskell/*` packages enables support for haskell profiling libraries. Profiling libraries are used when you link programs that use those profling libraries with `ghc -prof` or via `cabal install --enable-library-profiling`.

As `stack` is both a library and binary `USE=profile` enables profiling support for stack library. To use profiled stack library you need to build all it's dependencies with `USE=profile`. That's why `emerge` asks you to enable more and more of that flag for other packages. This is not very convenient but expected.

But!

`stack --profile` looks unrelated to `USE=profile` in `stack`. Does `stack install --profile` fails for you if you try to use it without stack built as `USE=profile`?

**Comment by VonFry** [comment]
Thank you, and the second problem have fixed by myself.
