### ISSUE TITLE
Add dev-haskell/ghcjs-8.6 and dev-haskell/ghcjs-8.4?

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/gentoo-haskell#906]
If `ghcjs-8.x` exists as an executable, I could use it in cabal projects by putting the following lines in `cabal.project`.

```
with-compiler: /usr/bin/ghcjs-8.x
compiler: ghcjs
 
packages: .
```

https://launchpadlibrarian.net/405637152/ghcjs-8.4_8.4.0.1+git20181210.3.00a8993a-1~14.04.dsc describes build-time dependencies. https://launchpad.net/~hvr/+archive/ubuntu/ghcjs/ is ghcjs PPA.

https://www.reddit.com/r/haskell/comments/ajk9th/you_dont_need_reflexplatform_to_use_ghcjs_or/eewrzp9/ explains more details.

**Comment by trofi** [comment]
These links contain very little. They even lack the homepage link. I don;t think ghcjs is a native target for ghc today.

Did you succeed building ghcjs mahually? If you did please post sequence of commands you used. We can evaluate if it's something `::haskell` can maintain.

**Comment by crocket** [comment]
A few months ago, I might have worked hard on this issue. Now, I want to minimize maintenance.
Since I no longer do web development or any form of professional development, I am going to close it for now.

**Comment by hololeap** [comment]
The steps to building this manually are outlined [here](https://github.com/ghcjs/ghcjs#quick-start---developing-ghcjs).

I followed the __getting and preparing the source tree__ instructions and ran `bash -x utils/makePackages.sh 2>&1 | tee makePackages.log` instead of the last command. You can see the output [here](https://gist.github.com/e9bbab6cba97824055480320ef0aa5ad). It also required `dev-haskell/alex` to be installed.

**Comment by hololeap** [comment]
I think I'm [off to a good start](https://github.com/hololeap/gentoo-haskell/tree/ghcjs/dev-lang/ghcjs) with creating a ghcjs ebuild, but I'm running into issues because it expects GHC from a [certain snapshot](https://github.com/ghc/ghc/commit/fd6cbeab07). This means it can't build directly from the system's GHC but has to clone a git submodule and build using that. This makes things a bit more complicated.

**Comment by crocket** [comment]
My crude conclusion is that it is better for you to wait for asterius or WebGHC.
