### ISSUE TITLE
bump aeson version to 1.4.4.0

### ISSUE THREAD

**Issue by madjestic** [gentoo-haskell/gentoo-haskell#951]
Hey guys,

Is there a reason not to bump aeson to latest?

Cheers,
Vlad

**Comment by trofi** [comment]
Should be fixed by https://github.com/gentoo-haskell/gentoo-haskell/pull/952

**Comment by solpeth** [comment]
Just noticing that this appears to be causing a downgrade to `aeson-1.3.1.1`, unless I'm missing something else locally.

For those with `FEATURES=test` there is also the requirement to bump up to `quickcheck-instances-0.3.21` which requires the latest quickcheck, which is not yet available due to too many upper bound conflicts.

Shall we roll back the update?

**Comment by nl169** [comment]
works on my machine

**Comment by solpeth** [comment]
yes, it appears to be due to the unmet `quickcheck-instances` dependency affecting those with `FEATURES=test` enabled.
