### ISSUE TITLE
dependency issue? May not be a bug?

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#980]
I ran into a slot conflict because Stack doesn't want the latest versions of a few packages. In order to work around it, I added this to my package.mask:
```
=dev-haskell/tls-1.5.1::haskell
=dev-haskell/generic-deriving-1.13::haskell
=dev-haskell/memory-0.15.0::haskell
=dev-haskell/cryptonite-0.26-r1::haskell
=dev-haskell/hpack-0.33.0::haskell
```
That might be masking more than I needed, but it worked.

**Comment by pbarill** [comment]
It makes sense, given the dependencies of stack. Those upper bounds are in the ebuild for the latest ~arch in the repository (1.9.3.1):

    <dev-haskell/generic-deriving-1.13
    <dev-haskell/tls-1.5
    <dev-haskell/memory-0.15
    <dev-haskell/cryptonite-0.26
    <dev-haskell/hpack-0.32

A natural question: Any good reason why there isn't a more recent version available? I don't use stack right now, but let me see...

**Comment by pbarill** [comment]
The problem is that `stack-1.9.3.1` is the last release that requires `ansi-terminal >= 0.8`. Any version past this calls for 0.9 or more, and that's a problem [for a lot of stuff](https://packdeps.haskellers.com/reverse/ansi-terminal). But if it so happens that you have nothing in conflict with `ansi-terminal >= 0.9`, you can give this a try by unmasking `ansi-terminal` and `stack` (though a few extra ebuilds would be needed to complete this). And there could be more fun issues like this in the process (lots of requirements -> lots of potential issues).

**Comment by Hypoon** [comment]
Thank you for looking into it. I'm happy to help in any way that I can, but it sounds like you understand the problem pretty well. What would the portage developers say is the solution?

**Comment by pbarill** [comment]
One thing you can try is to install stack independently of portage:
https://docs.haskellstack.org/en/stable/README/

Will it work? Would it bring compatibility issues? I can't say. The one time I tried stack it ignored the system's ghc and wanted to pull in another ghc. That was a turnoff for me, but we might take this as an indication that it is indeed making an isolated environment.

**Comment by solpeth** [comment]
@Hypoon there was a large set of updates pushed through recently, and with that there is a chance of conflicts (especially with haskell packages). I'll get to sorting through the required masks when I can.

@pbarill for clarity, we don't recommend installing haskell packages without Portage. But you are correct in pointing out the reason why stack has not yet been bumped past 1.9.3.1.
